language: c
os: linux
dist: focal

addons:
    apt:
        packages:
            - g++
            - nasm
            - xorriso
            - grub-common
            - mtools
            - libmount-dev
            - libselinux-dev
            - build-essential 
            - libtool 
            - pkg-config 
            - intltool
            - libglib2.0-dev 
            - libfdt-dev 
            - libpixman-1-dev 
            - zlib1g-dev 
            - libaio-dev 
            - libbluetooth-dev 
            - libbrlapi-dev 
            - libbz2-dev  
            - libcap-dev 
            - libcap-ng-dev 
            - libcurl4-gnutls-dev 
            - libgtk-3-dev 
            - libibverbs-dev 
            - libjpeg8-dev 
            - libncurses5-dev 
            - libnuma-dev 
            - librbd-dev 
            - librdmacm-dev 
            - libsasl2-dev 
            - libsdl1.2-dev 
            - libseccomp-dev 
            - libsnappy-dev 
            - libssh2-1-dev 
            - libvde-dev 
            - libvdeplug-dev 
            - libxen-dev 
            - liblzo2-dev 
            - valgrind 
            - xfslibs-dev
            - libpulse-dev 
            - libpulse0
            - grub-pc-bin
            - ninja-build

cache:
    directories:
        - $HOME/qemu

env:
    - TRAVIS_ARCH=i386 QEMU_ARCHES=i386

jobs:
  include:
    - compiler: gcc
      env: COMPILER=g++

before_install:
    - export ARCH=$TRAVIS_ARCH
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi

before_script:
    - chmod +x travis-qemu/travis-qemu.sh
    - bash -e travis-qemu/travis-qemu.sh
    - export PATH=$PATH:$HOME/qemu/bin
    - qemu-system-i386 --version

script: ./.build-travis.sh
